### ISSUE TITLE
Deploy with Github Pages

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-ui-template#11]
We should make this UI deploy with GitHub pages

:)

**Comment by riusricardo** [comment]
SGTM. It will be more practical to add a selector instead of just pointing to the `dev-node.substrate.dev` node.

**Comment by shawntabrizi** [comment]
Yes, someone should do this:
https://github.com/substrate-developer-hub/substrate-ui-template/issues/9

**Comment by shawntabrizi** [comment]
This was super easy by following this:
https://github.com/gitname/react-gh-pages

Basically:

* `yarn add gh-pages`
* Update homepage
* Update scripts
* `yarn deploy`
* _magic_
